import Head from "next/head";
import Image from "next/image";
import { Banner, Card } from "../components";
import styles from "../styles/Home.module.css";
import coffeeStoreData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoreData,
    },
  };
}

export default function Home(props) {
  const buttonClicked = () => {
    console.log("clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee-stores App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          titleOne="Coffee"
          titleTwo="Connoisseur"
          buttonText="View Stores nearby"
          description="Discover your local coffee shops!"
          handleClick={buttonClicked}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="Hero image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores?.map((coffeeStore) => {
                return (
                  <Card
                    className={styles.card}
                    key={coffeeStore?.id}
                    href={`/coffee-stores/${coffeeStore.id}`}
                    imgUrl={coffeeStore.imgUrl}
                    name={coffeeStore?.name}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
